version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_mock_service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres-data: {}
