version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_mock_service
#    volumes:
#      - ./nds.sql:/docker-entrypoint-initdb.d/1-nds.sql
#      - ./nds_book_to_author.sql:/docker-entrypoint-initdb.d/2-nds.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432
