version: '3.1'

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - django-mock

  django-mock:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn mockservice.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_mock_service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env.db.prod

volumes:
  postgres-data: {}
