version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_mock_service
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432

volumes:
  postgres-data: {}
