# Generated by Django 4.1.1 on 2022-10-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_message_number_of_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(default='1234567890', max_length=30),
        ),
    ]
